### ISSUE TITLE
Develop OK v1 to OKv2 Klanten migration script

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-klant#197]
### Thema / Theme

Other

### Omschrijving / Description

Taiga DH 579

A script to migrate the Open Klant v1 Klanten to Open Klant v2 has been requested, for further details of which fields are to be migrated see the Taiga issue

**Comment by joeribekker** [comment]
Estimated on 5 days

**Comment by joeribekker** [comment]
@JanBrek ping

**Comment by PeterVanBragt** [comment]
At first glance, 5 days seems like a lot of work for a query. Can some more background information be provided on this?

**Comment by joeribekker** [comment]
@PeterVanBragt it's 2 different databases, so just a query won't cut it. Let's not downplay the work involved here.

However, if the scope is limited to "klanten" to be migrated to "partijen" (explicitly saved) and leave out "klanten" (ad hoc saved), things will be little easier since we don't need much logic. The tables however are really different, so we need to export it and then when importing, scatter the data over various tables.

There was a reason Open Klant had a major version bump. The data is not really compatible.

So. Maybe 4 days if no logic do distinct between partijen and klanten.

**Comment by PeterVanBragt** [comment]
Hi @joeribekker, I can hereby approve this issue!

**Comment by alextreme** [comment]
Discussed, migration script will be rounded up and an Open Klant release with it will be ready before the end of november
