### ISSUE TITLE
Versie en git hash tonen op startscherm Open Klant

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-klant#51]
Op het startscherm van Open Klant mag de versie en git hash getoond worden, zoals we dit ook al doen in Open Zaak en Open Notificaties:

![image](https://github.com/maykinmedia/open-klant/assets/226839/eddf935f-24a4-4d9c-a93f-1019b3a43842)

**Comment by alextreme** [comment]
@ErhanCitil dit werkt in een development omgeving, echter volgens mij niet wanneer je open klant in docker draait. Graag dit dubbelchecken

**Comment by ErhanCitil** [comment]
Aanteking voor me zelf:

Docker zegt 'fatal: not a git repository (or any of the parent directories): .git', ik heb geprobeerd Docker te runnen zonder dat .git in de .docker.ignore staat maar dat blijkt ook niet te werken.

**Comment by alextreme** [comment]
To doublecheck

**Comment by SonnyBA** [comment]
Currently both values are shown although the user has to login in order to see them (just like in [Open Zaak](https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/templates/master.html#L58) and [Open Notificaties](https://github.com/open-zaak/open-notificaties/blob/main/src/nrc/templates/master.html#L64)):


![Image](https://github.com/user-attachments/assets/706b81b7-195c-4413-8087-443f5c9e023d)



If we want to show these values too for anonymous users then some changes will have to be made (although this will make it inconsistent with the other mentioned applications).

One change we might want to do though is making this consistent across the projects like is done already for showing these values in the admin (see [ticket](https://github.com/maykinmedia/open-api-framework/issues/21)).

**Comment by joeribekker** [comment]
Versions should not be on the public page.
